ext {
    moduleLibraryName = "umamusume-localify-android"
    magiskModuleId = "umamusume_localify"
    moduleName = "UmamusumeLocalify"
    moduleAuthor = "Kimjio"
    moduleDescription = "umamusume-localify"
    moduleVersion = "3.1.0"
    moduleVersionCode = 32
    moduleUpdateJson = "https://raw.githubusercontent.com/Kimjio/umamusume-localify-android/main/update"
}
